# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScoreCompose < Formula
  desc ""
  homepage "https://github.com/rachfop/score-compose"
  version "0.9"

  on_macos do
    url "https://github.com/rachfop/score-compose/releases/download/v0.9/score-compose_0.9_darwin_all.tar.gz"
    sha256 "ddffdcd2530672963c08d8b0bc7f9ebda1fea81c61aff698a856f3887a38b518"

    def install
      bin.install "score-compose"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rachfop/score-compose/releases/download/v0.9/score-compose_0.9_linux_arm64.tar.gz"
      sha256 "1e471ebaf2c9f61e4581dce79cc7c21dddafe971b397d8ee5b53af00cbee59a7"

      def install
        bin.install "score-compose"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rachfop/score-compose/releases/download/v0.9/score-compose_0.9_linux_amd64.tar.gz"
      sha256 "fcbb7ee1be5988d01dc6da1b03125215d012ef59c34d7b42932ce58840466007"

      def install
        bin.install "score-compose"
      end
    end
  end
end
