# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScoreCompose < Formula
  desc ""
  homepage "https://github.com/rachfop/score-compose"
  version "0.11"

  on_macos do
    url "https://github.com/rachfop/score-compose/releases/download/v0.11/score-compose_0.11_darwin_all.tar.gz"
    sha256 "51de3dee2b625076c54311b960ebb155b82b3b60b29e095281aa7e63851160a4"

    def install
      bin.install "score-compose"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rachfop/score-compose/releases/download/v0.11/score-compose_0.11_linux_arm64.tar.gz"
      sha256 "8dbf759c281ab2fb661fbd1b62d6157e2514cd8194adc04920f960fe57eaa082"

      def install
        bin.install "score-compose"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rachfop/score-compose/releases/download/v0.11/score-compose_0.11_linux_amd64.tar.gz"
      sha256 "7f2cee13c868432080e486a16ec3e968be991ad98e325af332f65910e9e5b003"

      def install
        bin.install "score-compose"
      end
    end
  end
end
